language: scala
sudo: required
dist: trusty
addons:
  apt:
    update: true

jdk:
  - oraclejdk8

script:
  - curl -L -o ~/bin/mill https://github.com/lihaoyi/mill/releases/download/0.4.0/0.4.0-12-102ddf && chmod +x ~/bin/mill
  - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
  - export PATH=~/bin/mill:$PATH
  - mill __.test